spring.application.name=segrepass
server.port=${PORT:8080}

# Credenziali Segrepass (da env vars)
segrepass.username=${SEGREPASS_USERNAME:}
segrepass.password=${SEGREPASS_PASSWORD:}

# Logging
logging.level.root=INFO
logging.level.com.myuni.segrepass=DEBUG
logging.level.org.openqa.selenium=WARN

jwt.secret=THIS_IS_A_SECRET_KEY_FOR_JWT_TOKEN_GENERATION
jwt.access-expiration-ms=900000
jwt.refresh-expiration-ms=604800000
