spring.application.name=segrepass
server.port=${PORT:8080}

# Credenziali Segrepass (da env vars)
segrepass.username=${SEGREPASS_USERNAME:}
segrepass.password=${SEGREPASS_PASSWORD:}

# Logging
logging.level.root=INFO
logging.level.com.myuni.segrepass=DEBUG
logging.level.org.openqa.selenium=WARN
